version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:3000"
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_network
  dev-app:
    build:
      context: .
      dockerfile: Dockerfile-dev-app
    volumes:
      - /home:/home
    user: "66679:66049"
    networks:
      - app_network
    working_dir: /home/oschiavo/Devel/chat-with-gpt/app
    environment:
      - HOME=/home/oschiavo
    entrypoint: ["sh", "-c", "/usr/local/bin/npm start"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-app.rule=Host(`localhost`) && PathPrefix(`/`)"
      - "traefik.http.routers.dev-app.entrypoints=web"
      - "traefik.http.services.dev-app.loadbalancer.server.port=3000"

    
  dev-srv:
    build:
      context: .
      dockerfile: Dockerfile-dev-srv
    volumes:
      - /home:/home
    user: "66679:66049"
    networks:
      - app_network
    working_dir: /home/oschiavo/Devel/chat-with-gpt/server
    environment:
      - HOME=/home/oschiavo      
      - S3_BUCKET=wengo-chatwithgpt
      - DEFAULT_S3_REGION=eu-west-3
    entrypoint: ["sh", "-c", "while (true); do sleep 3600 ; done "]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-srv.rule=Host(`localhost`) && PathPrefix(`/chatapi`)"
      - "traefik.http.routers.dev-srv.entrypoints=web"
      - "traefik.http.services.dev-srv.loadbalancer.server.port=3001"
  cube_api:
    restart: always
    image: cubejs/cube:latest
    ports:
      - 4000:4000
    env_file:
      - path: ./.env.cube
    volumes:
      - .:/cube/conf
networks:
  app_network:
    driver: bridge
