FROM node:19-bullseye-slim AS server

COPY MYBESTPRO-CA.crt /usr/local/share/ca-certificates/
COPY WENGO.PRIV-CA.crt /usr/local/share/ca-certificates/

ENV NODE_EXTRA_CA_CERTS /etc/ssl/certs/ca-certificates.crt

# Set the working directory
WORKDIR /app

# Update the package index and install required dependencies
RUN apt-get update && \
    apt-get install -y \
    curl \
    build-essential \
    git \
    libssl-dev \
    libffi-dev \
    python3-dev \
    python3-pip \
    openssl \
    ca-certificates && \
    update-ca-certificates


