FROM node:19-bullseye-slim AS server

# Set the working directory
WORKDIR /app

# Update the package index and install required dependencies
RUN apt-get update && \
    apt-get install -y \
    curl \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    python3-pip \
    openssl


